set_property -dict { PACKAGE_PIN Y18 IOSTANDARD LVCMOS33 } [get_port clk ]
set_property -dict { PACKAGE_PIN R1  IOSTANDARD LVCMOS33 } [get_port clr ]
set_property -dict { PACKAGE_PIN Y9  IOSTANDARD LVCMOS33 } [get_port en  ]

set_property -dict { PACKAGE_PIN W4  IOSTANDARD LVCMOS33 } [get_port {d[0]}]
set_property -dict { PACKAGE_PIN R4  IOSTANDARD LVCMOS33 } [get_port {d[1]}]
set_property -dict { PACKAGE_PIN T4  IOSTANDARD LVCMOS33 } [get_port {d[2]}]
set_property -dict { PACKAGE_PIN T5  IOSTANDARD LVCMOS33 } [get_port {d[3]}]
set_property -dict { PACKAGE_PIN U5  IOSTANDARD LVCMOS33 } [get_port {d[4]}]
set_property -dict { PACKAGE_PIN W6  IOSTANDARD LVCMOS33 } [get_port {d[5]}]
set_property -dict { PACKAGE_PIN W5  IOSTANDARD LVCMOS33 } [get_port {d[6]}]
set_property -dict { PACKAGE_PIN U6  IOSTANDARD LVCMOS33 } [get_port {d[7]}]

set_property -dict { PACKAGE_PIN Y8  IOSTANDARD LVCMOS33 } [get_port {wsel[0]}]
set_property -dict { PACKAGE_PIN Y7  IOSTANDARD LVCMOS33 } [get_port {wsel[1]}]
set_property -dict { PACKAGE_PIN W9  IOSTANDARD LVCMOS33 } [get_port {wsel[2]}]

set_property -dict { PACKAGE_PIN V5  IOSTANDARD LVCMOS33 } [get_port {rsel[0]}]
set_property -dict { PACKAGE_PIN R6  IOSTANDARD LVCMOS33 } [get_port {rsel[1]}]
set_property -dict { PACKAGE_PIN T6  IOSTANDARD LVCMOS33 } [get_port {rsel[2]}]

set_property -dict { PACKAGE_PIN A21 IOSTANDARD LVCMOS33 } [get_port {q[0]}]
set_property -dict { PACKAGE_PIN E22 IOSTANDARD LVCMOS33 } [get_port {q[1]}]
set_property -dict { PACKAGE_PIN D22 IOSTANDARD LVCMOS33 } [get_port {q[2]}]
set_property -dict { PACKAGE_PIN E21 IOSTANDARD LVCMOS33 } [get_port {q[3]}]
set_property -dict { PACKAGE_PIN D21 IOSTANDARD LVCMOS33 } [get_port {q[4]}]
set_property -dict { PACKAGE_PIN G21 IOSTANDARD LVCMOS33 } [get_port {q[5]}]
set_property -dict { PACKAGE_PIN G22 IOSTANDARD LVCMOS33 } [get_port {q[6]}]
set_property -dict { PACKAGE_PIN F21 IOSTANDARD LVCMOS33 } [get_port {q[7]}]