@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Mon May 05 17:23:31 +0800 2025
REM SW Build 5239630 on Fri Nov 08 22:35:27 MST 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
REM elaborate design
echo "xelab --incr --debug typical --relax --mt 2 -L xil_defaultlib -L axi_bram_ctrl_v4_1_11 -L axi_lite_ipif_v3_0_4 -L lib_cdc_v1_0_3 -L interrupt_control_v3_1_5 -L axi_gpio_v2_0_35 -L generic_baseblocks_v2_1_2 -L fifo_generator_v13_2_11 -L axi_data_fifo_v2_1_32 -L axi_infrastructure_v1_1_0 -L axi_register_slice_v2_1_33 -L axi_protocol_converter_v2_1_33 -L blk_mem_gen_v8_4_9 -L axi_crossbar_v2_1_34 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot soc_simu_behav xil_defaultlib.soc_simu xil_defaultlib.glbl -log elaborate.log"
call xelab  --incr --debug typical --relax --mt 2 -L xil_defaultlib -L axi_bram_ctrl_v4_1_11 -L axi_lite_ipif_v3_0_4 -L lib_cdc_v1_0_3 -L interrupt_control_v3_1_5 -L axi_gpio_v2_0_35 -L generic_baseblocks_v2_1_2 -L fifo_generator_v13_2_11 -L axi_data_fifo_v2_1_32 -L axi_infrastructure_v1_1_0 -L axi_register_slice_v2_1_33 -L axi_protocol_converter_v2_1_33 -L blk_mem_gen_v8_4_9 -L axi_crossbar_v2_1_34 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot soc_simu_behav xil_defaultlib.soc_simu xil_defaultlib.glbl -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
